AppointmentSystem/urls.py
from django.contrib import admin
from django.urls import path, include,re_path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404
from Settings import views
from django.views.static import serve

handler404 = views.custom_404_view

urlpatterns = [
    path('path_0d5a8632e95117ed76def8fb18ba2176162d540d7d1/', admin.site.urls),
    path(route='', view=include('Appointments.urls')),
    path(route='hakkimizda/', view=include('About.urls')),
    path(route='kullanici/', view=include('User.urls')),
    path(route='iletisim/', view=include('Contact.urls')),
]

if not settings.DEBUG:
    
    urlpatterns += re_path(
       r'^static/(?P<path>.*)$', serve, dict(document_root=settings.STATIC_ROOT)),
    urlpatterns += re_path(
       r'^media/(?P<path>.*)$', serve, dict(document_root=settings.MEDIA_ROOT)),
else:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Appointments/urls.py
from django.urls import path
from .views import (
    IndexView,
    InstructorListView,
    LoadMoreContentView,
    SearchInstitution,
    Search,
    MakeAppointmentView,
    CreateAppointmentView,
    GetAppointmentTimes,
    UserAppointmentsList,
    EditAppointmentVerifiedUser,
    DeleteAppointment,
    UpdateCreatedAppointment,
    DeleteCreatedAppointment
)   


urlpatterns = [
    path(route='', view=IndexView.as_view(), name='index'),
    path(route='ögretim-görevlileri/', view=InstructorListView.as_view(), name='instructor_list'),
    path(route='ogretim-gorevlileri/daha-fazla-yukle/', view=LoadMoreContentView.as_view(), name='load_more'),
    path(route='ogretim-gorevlileri/kurum-arama/', view=SearchInstitution.as_view(), name='search_institution'),
    path(route='ogretim-gorevlileri/arama/', view=Search.as_view(), name='search'),
    path(route='randevu-al/<slug:slug>', view=MakeAppointmentView.as_view(), name='make_appointment'),
    path(route='randevu-olustur', view=CreateAppointmentView.as_view(), name='create_appointment'),
    path('get-times/<slug:slug>', GetAppointmentTimes.as_view(), name='get_times'),
    path('alinan-randevular/', UserAppointmentsList.as_view(), name='user_appointment_list'),
    path('alinan-randevuyu/düzenle/<int:id>/', EditAppointmentVerifiedUser.as_view(), name='edit_appointment'),
    path('alinan-randevuyu/sil/<int:id>/', DeleteAppointment.as_view(), name='delete_appointment'),
    path('olusturulan-randevuyu/güncelle/<int:id>/',view=UpdateCreatedAppointment.as_view(), name='updated_created_appointment' ),
    path('olusturulan-randevuyu/sil/<int:id>/', view=DeleteCreatedAppointment.as_view(), name='delete_created_appointment' )
]

User/urls.py
from django.urls import path
from .views import (
    LoginView,
    LogoutView,
    RegisterView,
    ProfileView,
    PasswordChange,
    PasswordResetRequestView,
    PasswordResetConfirmView,
    PasswordResetDone
)
from .send_mail import activate_account


urlpatterns = [
    path(route='giris-yap/', view=LoginView.as_view(),name='login'),
    path(route='cikis-yap/', view=LogoutView.as_view(), name='logout'),
    path("kayit-ol/", RegisterView.as_view(), name="register"),
    path("activate/<uidb64>/<token>/", activate_account, name="activate"),
    path(route='profil/', view=ProfileView.as_view(), name='profile'),
    path(route='parola-degistirme/', view=PasswordChange.as_view(), name='password_change'),
    path(route='parola-sifirlama/', view=PasswordResetRequestView.as_view(), name='password_reset_request' ),
    path(route='parola-sifirlama/<uid>/<token>/', view=PasswordResetConfirmView.as_view(), name='password_reset_confirm' ),
     path(route='parola-sifirlama/basarili', view=PasswordResetDone.as_view(), name='password_reset_done' )
]

User/models/user_profile_model.py
from django.contrib.auth.models import User
from django.utils.text import slugify
from django.db import models
import random

class TitleModel(models.Model):
    title = models.CharField(
        verbose_name='Başlık',
        max_length=150
    )

    class Meta:
        db_table = 'title_model'
        managed = True
        verbose_name = 'Başlık'
        verbose_name_plural = 'Öğretim Görevlileri Başlıkları'

    def __str__(self):
        return self.title

class Institution(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name
    
    class Meta:
        db_table = 'Institution'
        managed = True
        verbose_name = 'Kurum'
        verbose_name_plural = 'Kurumlar'
        ordering = ['-id']

class UserProfile(models.Model):
    institution = models.ForeignKey(
        Institution, 
        on_delete=models.CASCADE,
        default='',
        null=True,
        blank=True
    )
    title = models.ForeignKey(TitleModel, on_delete=models.CASCADE, default='', null=True, blank=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile',verbose_name="Kullanıcı", error_messages={'unique':'Kullanıcı adı sistemde kayıtlı'})
    bio = models.TextField(verbose_name='Kullanıcı Biyografisi',max_length=500, blank=True, null=True)
    
    profile_picture = models.ImageField(verbose_name='Kullanıcı Profil Resmi',upload_to='profile_pictures/', blank=True, null=True, default='defaults/logo.jpg')
    is_verified = models.BooleanField(default=False, verbose_name="Kullanıcı yetkili mi ?")  
    is_active = models.BooleanField(default=False, verbose_name='Kullanıcı aktif mi ?')
    slug = models.SlugField(unique=True, blank=True) 
    contact_email = models.EmailField(verbose_name='Kullanıcıların size ulaşabileceği e-posta adresi', null=True, blank=True)


    def __str__(self):
        return self.user.username
    
    def save(self, *args, **kwargs):
        if not self.slug:
            slug_value = f'{self.user.first_name}-{self.user.last_name}-{(random.randint(1,99999))}'
            self.slug = slugify(slug_value.replace('ı','i'))
        super().save(*args, **kwargs)

    class Meta:
        db_table = 'user_profile'
        managed = True
        verbose_name = 'profil'
        verbose_name_plural = 'Kullanıcı Profilleri'

Appointments/views/appointment_edit.py
from django.views.generic import View
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from ..models import AppointmentCreation, AppointmentDetails
from User.send_mail import send_email_with_template
from ..mixins import VerifiedUserMixin
from ..forms import CreateAppointmentForm
from User.models import UserProfile

class UpdateCreatedAppointment(VerifiedUserMixin,View):
    template_name = "appointment/created-appointment-update.html"
    def get(self, request, *args, **kwargs):
        id = kwargs.get('id', None)
        if id is not None:
            appointment = AppointmentCreation.objects.get(id=id)
            form = CreateAppointmentForm(initial={
                'date':appointment.date,
                'time':appointment.time,
                'appointment_is_active':appointment.appointment_is_active
            })

            return render(
                request=request,
                template_name=self.template_name,
                context={'form': form}
            )
        else:
            return redirect('create_appointment')
        
    def post(self, request, *args, **kwargs):
        form = CreateAppointmentForm(request.POST)
        id = kwargs.get('id', None)
        if form.is_valid():
            user_profile = UserProfile.objects.get(user=request.user)
            appointment = AppointmentCreation.objects.get(id=id)
        
            try:
                appointment_details = AppointmentDetails.objects.get(appointment=appointment, appointment__staff_member=user_profile)
                appointment.time = form.cleaned_data.get('time') 
                appointment.date = form.cleaned_data.get('date')
                appointment.appointment_is_active = form.cleaned_data.get('appointment_is_active')
                appointment.save()
                send_email_with_template(
                        user=appointment_details.customer.user,
                        subject="Randevunuz düzenlendi",
                        message=f'{appointment.staff_member.user.get_full_name()} Adlı öğretim görevlisinden aldığınız {appointment.date} {appointment.time} tarihli randevunuz düzenlendi. Yeni randevu {form.cleaned_data.get("date")} {form.cleaned_data.get("time")} randevunun aktiflik durumu { "Aktif" if form.cleaned_data.get("appointment_is_active") else "Dolu"} olarak düzenlendi.',
                        from_mail=appointment_details.customer.user.email,
                        link=None
                    
                    )
                messages.success(request, 'Randevunuz güncellendi.')
                       
                return redirect(request.path)
            except:
                    apointment_update = AppointmentCreation.objects.get(staff_member=user_profile, date=appointment.date, time=appointment.time)
                    apointment_update.time = form.cleaned_data.get('time') 
                    apointment_update.date = form.cleaned_data.get('date')
                    apointment_update.appointment_is_active = form.cleaned_data.get('appointment_is_active')
                    apointment_update.save()
                    messages.success(request, 'Randevunuz güncellendi.')
                    return redirect(request.path)
        else:
            return redirect(request.path)


class DeleteCreatedAppointment(VerifiedUserMixin,View):
    def get(self, request, *args, **kwargs):
        appointment_id = kwargs.get('id')
        try:
            user_profile = UserProfile.objects.get(user=request.user)
            appointment = AppointmentCreation.objects.get(id=appointment_id, staff_member=user_profile)
            
            try:
                appointment_details = AppointmentDetails.objects.get(appointment=appointment)
                if not appointment_details.appointment.staff_member.user == request.user:
                    return redirect('create_appointment')
                
                appointment.delete()
                send_email_with_template(
                    user=appointment_details.customer.user,
                    subject=f'Randevunuz Silindi',
                    message=f'{appointment.date} {appointment.time} Tarihi için {appointment_details.appointment.staff_member.user.get_full_name()} Adlı öğretim görevlisinden Almış olduğunuz randevu silindi.',
                    from_mail=appointment_details.customer.user.email,
                    link=None
                )
                

            except:
                appointment.delete()
                send_email_with_template(
                user=appointment.staff_member.user,
                subject=f'Randevunuz Silindi',
                message=f'{appointment.date} {appointment.time} Tarihi için oluşturmuş olduğunuz randevuyu sildiniz.',
                from_mail=appointment.staff_member.user.email,
                link=None
            )

            
            return redirect('create_appointment')  
        
        except AppointmentDetails.DoesNotExist:
            
            return redirect('create_appointment')  


class DeleteAppointment(VerifiedUserMixin, View):
    def post(self, request, *args, **kwargs):
        appointment_id = kwargs.get('id')
        try:
            user_profile = UserProfile.objects.get(user=request.user)
            try:
                appointment = AppointmentDetails.objects.get(id=appointment_id, appointment__staff_member=user_profile)
            except:
                return redirect('user_appointment_list')

            send_email_with_template(
                user=appointment.customer.user,
                subject=f'Randevunuz Silindi',
                message=f'{appointment.appointment.staff_member.user.get_full_name()} Adlı öğretim görevlisinden {appointment.appointment.date} {appointment.appointment.time} Tarihinde  aldığınız randevu silinmiştir. ',
                from_mail=appointment.customer.user.email,
                link=None
            )
            appointment.delete()
            messages.success(
                request=request,
                message='Randevu başarıyla silindi.'
            )
            return redirect('user_appointment_list')  
        
        except AppointmentDetails.DoesNotExist:
            messages.error(
                request=request,
                message='Randevu silinemedi! Tekrar deneyin.'
            )
            return redirect('user_appointment_list')  

class EditAppointmentVerifiedUser(VerifiedUserMixin, View):
    def post(self, request, *args, **kwargs):
        appointment_id = kwargs.get('id')
        try:
            user_profile = UserProfile.objects.get(user=request.user)
            appointment = AppointmentDetails.objects.get(id=appointment_id, appointment__staff_member=user_profile )
            user = appointment.customer.user
            status = request.POST.get('status')

            if status == 'Onaylandı':
                send_email_with_template(
                    user=user,
                    subject=f'Randevunuz {status}',
                    message=f'{appointment.appointment.staff_member.user.get_full_name()} Adlı öğretim görevlisinden {appointment.appointment.date} {appointment.appointment.time} tarihi için  aldığınız randevu onaylanmıştır. ',
                    from_mail=user.email,
                    link=None
                )
            elif status == 'İptal Edildi':
                appointment_creation = appointment.appointment
        
                appointment_creation.appointment_is_active = True
                appointment_creation.save()
                send_email_with_template(
                    user=user,
                    subject=f'Randevunuz {status}',
                    message=f'{appointment.appointment.staff_member.user.get_full_name()} Adlı öğretim görevlisinden {appointment.appointment.date} {appointment.appointment.time} tarihinde aldığınız randevu iptal edilmiştir. ',
                    from_mail=user.email,
                    link=None
                )
            appointment.status = status
            appointment.save()

        except AppointmentDetails.DoesNotExist:
            
            return redirect('user_appointment_list')  

        return redirect('user_appointment_list')

Appointments/views/create_appointment.py
from django.views.generic import View
from ..mixins import VerifiedUserMixin
from ..forms import CreateAppointmentForm
from django.shortcuts import render, redirect
from django.contrib import messages
from ..models import AppointmentCreation
from User.models import UserProfile
from datetime import datetime
from django.http import JsonResponse
    

class CreateAppointmentView(VerifiedUserMixin,View):
    template_name = 'appointment/create-appointment.html'
    
    def get(self, request, *args, **kwargs):
        form = CreateAppointmentForm()
        _profile = UserProfile.objects.get(user=request.user)
        _appointmentList = AppointmentCreation.objects.filter(staff_member=_profile).order_by('-id')
       
        return render(
            request=request,
            template_name=self.template_name,
            context={'form':form,'appointments':_appointmentList}
        )

    def post(self, request, *args, **kwargs):
        form = CreateAppointmentForm(request.POST)
      
        if form.is_valid():
            date = form.cleaned_data.get('date')
            time = form.cleaned_data.get('time')
            is_active = form.cleaned_data.get('appointment_is_active')
            user_profile = UserProfile.objects.get(user=request.user)
            _control = AppointmentCreation.objects.filter(
                staff_member=user_profile,
                date=date,
                time=time
            )
            if _control.exists():
                messages.error(
                    request=request,
                    message='Aynı tarih için oluşturulan randevunuz var, lütfen başka tarih seçiniz.'
                )
                return redirect(request.path)
            AppointmentCreation.objects.create(
                staff_member=user_profile,  
                date=date,
                time=time,
                appointment_is_active=is_active
            )
            messages.success(
                request=request,
                message='Randevu başarıyla oluşturuldu'
            )
            return redirect(request.path)
        else:
            print(form.errors)
            messages.error(
                request=request,
                message='Randevu oluşturulamadı, tekrar deneyin'
            )
            return redirect(request.path)

Appointments/views/index_view.py
from django.views.generic.base import TemplateView
from django.views.generic import View
from Contact.forms import ContactForm
from django.shortcuts import render, redirect
from User.models import UserProfile
from ..models import AppointmentCreation

class IndexView(View):
    template_name = 'app/index.html'
    def get(self, request, *args, **kwargs):
        profiles = UserProfile.objects.filter(is_verified=True)
        _ = AppointmentCreation.objects.filter(staff_member__in=profiles).values('staff_member')

        profiles = UserProfile.objects.filter(user__in=_)[:20]
        contact_form = ContactForm()
        return render(
            request=request,
            template_name=self.template_name,
            context={
                'form':contact_form,
                'profile':profiles
            }
        )

templates/appointment/book-appointment.html
{% extends "base.html" %} {% block container %}
<section class="book-appointment-section">
  <h1 class="appointment-title">Randevu Al</h1>

  <div class="appointment-container">
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                {{ message }}
            </li>
            {% endfor %}
        </ul>
        {% endif %}
    <div class="profile">
      <img
        src="{{profile.profile_picture.url}}"
        alt=""
      />
      <div class="profile-container">
        <h1 class="profile-name">
          {% if profile.title is not None  %}
            
          {{profile.title}}
          {% endif %}
          {% if profile.user.first_name is not None %}
              {{profile.user.first_name}}
          {% endif %}
          {% if profile.user.last_name is not None %}
              {{profile.user.last_name}}
          {% endif %}
          </h1>
        <span class="about">
          {% if profile.bio is not None %}
            
          {{profile.bio}}
            {% else %}
              Biyografi yok.
          {% endif %}
        </span>
        <div class="profile-contact-div">
          {% if profile.contact_email is not None %}
            
          <i class="fas fa-envelope"></i>
          <span>{{profile.contact_email}}</span>
          {% endif %}
        </div>
      </div>
    </div>

    
    {% if appointment %}
      
    <div class="book-appointment-container">
      <form method="POST">
       
        {% csrf_token %}
        <h1>Uygun Randevu Tarihleri</h1>
        <select class="appointment-date-select" name="appointment_date">
          <option value="">Tarih Seçin</option>
          {% for item in appointment %}
            <option value="{{item}}">{{item}}</option>
          {% endfor %}
          
         
        </select>
        <select class="appointment-time-select" name="appointment_time">
          <option value="">Saat Seçin</option>

        </select>
        {{form.appointment_type}}
        <span>Randevu sürenizi girin</span>
        {{form.time}}
        
        {{form.content}}
        <button type="submit" class="form-button">Randevu al</button>
      </form>
      </div>
      {% endif %}
    </div>
  </section>
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script>

    $(document).ready(function(){

      $('.appointment-date-select').change(function(){
        var selected_date = $(this).val();
        var userSlug = "{{ profile.slug|escapejs }}";
        console.log(userSlug)
        const timeSelect = $('.appointment-time-select'); // Saat select 
        timeSelect.html('<option value="">Saatler yükleniyor...</option>');
        $.ajax({
                url: '/get-times/'+userSlug, 
                data: { date: selected_date, slug:userSlug }, 
                success: function (data) {
                    timeSelect.empty();

                    if (data.times && data.times.length > 0) {
                        $.each(data.times, function (index, time) {
                            timeSelect.append(new Option(time, time));
                        });
                    } else {
                        timeSelect.append(new Option('Bu tarih için uygun saat yok', ''));
                    }
                },
                error: function (e) {
                    timeSelect.html('<option value="">Saatler yüklenemedi</option>');
                    console.log(e.message)
                }
            });
      })
    })


  </script>
  {% endblock container %}

templates/appointment/create-appointment.html
{% extends "base.html" %}
{% load static %}



{% block container %}
<section class="create-appointment">
  <div class="create-appointment-title">Randevu Oluştur</div>

  <form method="POST">
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
            {{ message }}
        </li>
        {% endfor %}
    </ul>
    {% endif %}
    {% csrf_token %}
    <div class="input-container">
      <label for="">Randevu Tarihi</label>
      {{form.date}}
    </div>
    <div class="input-container">
      <label for="">Randevu Saati</label>
      {{form.time}}
    </div>
    <div class="input-container">
      <label for="">Randevu Durumu</label>
      {{form.appointment_is_active}}
    </div>
    <button type="submit">Randevu Oluştur</button>
  </form>
</section>
<section class="appointment-user-section">
  <span class="appointment-title">Oluşturulan Randevularınız</span>

  <div class="table-container">
    <table class="appointment-table">
      <thead>
        <tr>
          <th>Eğitmen</th>
          <th>Randevu Durumu</th>
          <th>Randevu Tarihi</th>
          <th>Randevuyu Düzenle</th>
          <th>Randevuyu Sil</th>
        </tr>
      </thead>
      <tbody class="appointment-table">
        {% for item in appointments  %}

        <tr>
          <td>{{item.staff_member.user.get_full_name}}</td>
          {% if item.appointment_is_active %}
            <td style="color: #66FF00;">Boş</td>

          {% else %}
            <td style="color: #EF0107;">Dolu</td>
          {% endif %}
          
          <td>{{item.date|date:"d.m.Y"}} {{item.time|time:"H:i"}}</td>
      
          <td>
            <a href="{% url 'updated_created_appointment' id=item.id %}">Düzenle</a>
          </td>

          
          <td>
            <a href="{% url 'delete_created_appointment' id=item.id %}">Randevuyu Sil</a>
          </td>
        </tr>
        {% endfor %}
       
      </tbody>
    </table>
  </div>
  
</section>

{% endblock container %}

templates/appointment/created-appointment-update.html
{% extends "base.html" %}
{% load static %}



{% block container %}
<section class="create-appointment">
  <div class="create-appointment-title">Randevu Güncelleme</div>

  <form method="POST">
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
            {{ message }}
        </li>
        {% endfor %}
    </ul>
    {% endif %}
    {% csrf_token %}
    <div class="input-container">
      <label for="">Randevu Tarihi</label>
      {{form.date}}
    </div>
    <div class="input-container">
      <label for="">Randevu Saati</label>
      {{form.time}}
    </div>
    <div class="input-container">
      <label for="">Randevu Durumu</label>
      {{form.appointment_is_active}}
    </div>
    <button type="submit">Randevuyu Güncelle</button>
  </form>
</section>

{% endblock container %}

templates/appointment/edit-appointment.html
{% extends "base.html" %}
{% load static %}



{% block container %}
<section class="create-appointment">
  <div class="create-appointment-title">Randevu Düzenle</div>

  <form method="POST">
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
            {{ message }}
        </li>
        {% endfor %}
    </ul>
    {% endif %}
    {% csrf_token %}
    <div class="input-container">
      <label for="">Randevu Tarihi</label>
      {{form.date}}
    </div>
    <div class="input-container">
      <label for="">Randevu Saati</label>
      {{form.time}}
    </div>
    <div class="input-container">
      <label for="">Randevu Durumu</label>
      {{form.appointment_is_active}}
    </div>
    <button type="submit">Randevu Oluştur</button>
  </form>
</section>
{% endblock container %}

templates/appointment/profile-appointment.html
{% extends "base.html" %} {% load static %} {% block container %}

<section class="appointment-list-section">
  <h1>Randevu Al</h1>
  <div class="search-container">
    <input
      type="search"
      name=""
      id="search-instructor"
      placeholder="Eğitmen Ara"
    />
    <select name="" id="academic-departments">
      <option value="">Akademik Birim Seç</option>
      {% for item in institution_list %}
      <option value="{{item.id}}">{{item.name}}</option>
      {% endfor %}
    </select>
  </div>
  <div class="appointment-container">
    {% for item in users %}

    <div class="profile-card">
      <img src="{{item.profile_picture.url}}" alt="" id="user-profile-image" />
      <div class="user-profile">
        <span class="user-name"
          >{% if item.title %}
            {{item.title}}
          {% endif %} {{item.user.first_name}} {{item.user.last_name}}</span
        >
        <span class="user-about">{{item.bio}}</span>
        <div class="user-footer">
          {% if item.contact_email is not None %}
            
          <div class="user-email">
            <i class="bi bi-envelope"></i>
            <span>{{item.contact_email}}</span>
          </div>
          {% endif %}
          <div class="appointment-detail">
            <i class="bi bi-arrow-right"></i>
            <a href="{% url 'make_appointment' slug=item.slug  %}">Randevu Al</a>
          </div>
        </div>
      </div>
    </div>

    {% endfor %}
  </div>

  <button class="load-more" type="button" data-offset="10">Daha Fazla</button>
</section>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
  $(document).ready(function () {
    $("#search-instructor").keyup(function () {
      let search = $(this).val();
  
      $.ajax({
        url: '{% url "search" %}',
        data: {
          search: search,
        },

        success: function (response) {
          
          var html = ''
          $(".appointment-container").empty();
            response.data.forEach(function(item){
              
              console.log(email)
              html += `
<div class="profile-card">
      <img
        src="${item.profile_picture}"
        alt=""
        id="user-profile-image"
      />
      <div class="user-profile">
        <span class="user-name">${item.title} ${item.first_name} ${item.last_name}</span>
        <span class="user-about"
          >${item.bio}</span
        >
        <div class="user-footer">
          <div class="user-email">
            <i class="bi bi-envelope"></i>
              <span>${item.contact_email}</span>
          </div>
          <div class="appointment-detail">
            <i class="bi bi-arrow-right"></i>
             <a href= '/randevu-al/${item.slug}'>Randevu Al</a>
          </div>
        </div>
      </div>
    </div>              
`;
            })
            
            $(".appointment-container").append(html);
          }
        
      });
    });
    $("#academic-departments").change(function () {
      let data = $(this).val();

      $.ajax({
        url: "{% url 'search_institution' %}",
        data: {
          value: data,
        },
        type: "GET",

        success: function (response) {
          $(".appointment-container").empty();
          if (response.data != "") {
            response.data.forEach(function (item) {
              console.log(item)
              var html = `
<div class="profile-card">
      <img
        src="${item.profile_picture}"
        alt=""
        id="user-profile-image"
      />
      <div class="user-profile">
        <span class="user-name">${item.title} ${item.first_name} ${item.last_name}</span>
        <span class="user-about"
          >${item.bio}</span
        >
        <div class="user-footer">
          <div class="user-email">
            
              <i class="bi bi-envelope"></i>
              <span>${item.contact_email}</span>
            
          </div>
          <div class="appointment-detail">
            <i class="bi bi-arrow-right"></i>
             <a href= '/randevu-al/${item.slug}'>Randevu Al</a>
          </div>
        </div>
      </div>
    </div>              
`;

              $(".appointment-container").append(html);
            });
          }
        },
      });
    });
   
    $(".load-more").click(function () {
   var offset = $(".appointment-container .profile-card").length;  // Count the number of profiles currently displayed
   $.ajax({
     url: "{% url 'load_more' %}",
     data: {
       offset: offset,
     },
     success: function (response) {
       if (response.content.length > 0) {
         response.content.forEach(function (item) {
           var postHtml = `
             <div class="profile-card">
                 <img
                   src="${item.profile_picture}"
                   alt=""
                   id="user-profile-image"
                 />
                 <div class="user-profile">
                   <span class="user-name">${item.title} ${item.first_name} ${item.last_name}</span>
                   <span class="user-about">${item.bio}</span>
                   <div class="user-footer">
                     <div class="user-email">
                       <i class="bi bi-envelope"></i>
                       <span>${item.contact_email}</span>
                     </div>
                     <div class="appointment-detail">
                       <i class="bi bi-arrow-right"></i>
                       <a href="/randevu-al/${item.slug}">Randevu Al</a>
                     </div>
                   </div>
                 </div>
             </div>
           `;
           $(".appointment-container").append(postHtml);
         });
       } else {
         $(".load-more").hide();  
       }
     }
   });
});
  });
</script>
{% endblock container %}